#pragma once

#define BLYNK_TEMPLATE_ID "YOUR_BLYNK_TEMPLATE_ID"
#define BLYNK_TEMPLATE_NAME "PlantSense AI Pod"
#define BLYNK_AUTH_TOKEN "YOUR_BLYNK_DEVICE_AUTH_TOKEN"

#define PLANTSENSE_WIFI_SSID "YOUR_WIFI_SSID"
#define PLANTSENSE_WIFI_PASSWORD "YOUR_WIFI_PASSWORD"
#define PLANTSENSE_AI_SERVER_URL "http://YOUR_SERVER_IP:5000/analyze"
